### ISSUE TITLE
Regarding `essential.defaults.loom`

### ISSUE THREAD

**Issue by kada49** [EssentialGG/essential-gradle-toolkit#18]
### Regarding `essential.defaults.loom`
Hey, I was thinking about the `essential.defaults.loom` property. At the moment there are 2 possibilities: `=0` and `=1`, where 1 hast mostly the newest versions. Would it be reasonable to create a third one `=2` for example to have:
- `=0` being one of the first revisions available, working. Not being updated except some bad issue is found and fabric/forge recommends to update.
- `=1` being a stable revision (`recommended` for forge), getting updated not so often.
- `=2` being 'always' the newest version available, updated more frequently

Note: `=1` and `=2` would be the same for fabric/yarn.
Note2: fabric loader is also updated according to what spot is is in
This would also be added to the Readme.

I am asking this because don't want to do it before knowing if it even has a chance to be added.

**Comment by Johni0702** [comment]
No, the primary purpose of `essential.defaults.loom` is not to specify which type of updates you want, it's to have no unexpected changes whatsoever.

When you add EGT to your project, you get forced to pick a `essential.defaults.loom` revision which determines the yarn/forge versions you get by default, and no future EGT update will change those.

This is so one can always bump their EGT dependency to get the latest bug fixes / features without having to fear being subjected to your mappings suddenly changing and having to update to the new names all over your code base (provided you'd even notice; there could even be subtle changes that might still compile but no longer function correctly).
One can then independently from EGT updates bump their declared `essential.defaults.loom` revision if one wishes to update to newer yarn/forge versions whenever most convenient.

Whenever a new Minecraft version is released, its default can be added to revision 0 because adding a new version doesn't affect existing users (they would have previously gotten an error if they tried to use it).
All subsequent revisions inherit from the previous revisions, so they too all immediately get the initial version.

If one then at a later point wishes to update the default for that Minecraft version, then one has to add an entirely new revision (e.g. 2) because changing any of the previous revisions could break the build for people already using those.

So while it may currently appear as if revision 1 is "the up-to-date revision", this is only because it's "the up-to-date revision when it was created" and "when it was created" is still reasonably close to now. It will not remain that way in the future. Only the latest revision will always be the most up-to-date.
